### ISSUE TITLE
Make separate files for neuron:neuron and neuron:region connectivity

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_connectomics_import#11]
We are working on refactoring the pipeline to remove bottlenecks.  In order to do this, we need to be able separate out neuron:neuron & neuron:region connectivity.  As far as I can tell, these two currently get bundled together in one OWL file for neuprint.  Can we separate them?

**Comment by admclachlan** [comment]
From https://github.com/VirtualFlyBrain/hemibrain_metadata/issues/21 (moving here as fixing this is probably easier to keep track of in a new issue)

"seems like neuron:type got loaded to KB via curation platform.

https://github.com/VirtualFlyBrain/curation/blob/admclachlan_curation/records/archive/newmeta_Xu2020NeuronsV1point1_201021.tsv

I thought this was also done with robot? We may need to switch in order to improve pipleline scaling as this will allow merging post triple-store."

Can confirm hemibrain neuron-region was loaded through curation platfrom and neuron-neuron with robot.

**Comment by admclachlan** [comment]
neuron:region connectomics will be loaded through OWL in the future so closing this.
Move to OWL here: https://github.com/VirtualFlyBrain/Management/issues/297
